<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Earnings Receipt #{{ $investment->id }}</title>
    <style>
        body { color: #1f2937; font-family: DejaVu Sans, sans-serif; font-size: 12px; line-height: 1.5; }
        h1 { color: #111827; font-size: 24px; margin-bottom: 4px; }
        h2 { border-bottom: 1px solid #d1d5db; color: #111827; font-size: 15px; margin-top: 24px; padding-bottom: 5px; }
        .subtitle { color: #6b7280; margin-bottom: 24px; }
        table { border-collapse: collapse; width: 100%; }
        td { border-bottom: 1px solid #e5e7eb; padding: 8px 4px; }
        td:first-child { color: #4b5563; font-weight: bold; width: 42%; }
        .footer { color: #6b7280; font-size: 10px; margin-top: 32px; text-align: center; }
        .highlight { background: #f0fdf4; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Earnings Receipt</h1>
    <div class="subtitle">Receipt for Investment #{{ $investment->id }} &middot; Generated on {{ $generatedAt->format('d F Y \a\t H:i') }}</div>

    <h2>Investment Summary</h2>
    <table>
        <tr><td>Investment ID</td><td>#{{ $investment->id }}</td></tr>
        <tr><td>Loan Reference</td><td>{{ $investment->loan->reference ?? 'N/A' }}</td></tr>
        <tr><td>Investment Amount</td><td>{{ $currency }} {{ number_format((float) $investment->amount, 2) }}</td></tr>
        <tr><td>Actual Return</td><td>{{ $currency }} {{ number_format((float) $investment->actual_return, 2) }}</td></tr>
        <tr class="highlight"><td>Total Earnings</td><td>{{ $currency }} {{ number_format($earnings, 2) }}</td></tr>
        <tr><td>Return on Investment (ROI)</td><td>{{ number_format($roi, 2) }}%</td></tr>
    </table>

    <h2>Loan Details</h2>
    <table>
        <tr><td>Loan Reference</td><td>{{ $investment->loan->reference ?? 'N/A' }}</td></tr>
        <tr><td>Loan Purpose</td><td>{{ $investment->loan->purpose ?? 'N/A' }}</td></tr>
        <tr><td>Loan Term</td><td>{{ $investment->loan->loan_term_days ?? '-' }} days</td></tr>
        <tr><td>Borrower</td><td>Borrower #{{ substr(md5($investment->loan->borrower_id ?? 0), 0, 8) }}</td></tr>
        <tr><td>Completed On</td><td>{{ $investment->completed_at ? $investment->completed_at->format('d F Y') : 'N/A' }}</td></tr>
    </table>

    <h2>Notes</h2>
    <p>This receipt confirms that the investment referenced above has been completed and earnings have been allocated. Please retain this receipt for your records. Funds are transferred directly between borrower and lender as per the platform's peer-to-peer model.</p>

    <div class="footer">Generated by {{ config('app.name') }}. This receipt is for record-keeping purposes only and does not constitute a financial guarantee.</div>
</body>
</html>
