<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Investment Statement #{{ $investment->id }}</title>
    <style>
        body { color: #1f2937; font-family: DejaVu Sans, sans-serif; font-size: 12px; line-height: 1.5; }
        h1 { color: #111827; font-size: 24px; margin-bottom: 4px; }
        h2 { border-bottom: 1px solid #d1d5db; color: #111827; font-size: 15px; margin-top: 24px; padding-bottom: 5px; }
        .subtitle { color: #6b7280; margin-bottom: 24px; }
        table { border-collapse: collapse; width: 100%; }
        td { border-bottom: 1px solid #e5e7eb; padding: 8px 4px; }
        td:first-child { color: #4b5563; font-weight: bold; width: 42%; }
        .footer { color: #6b7280; font-size: 10px; margin-top: 32px; text-align: center; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }
        .badge-active { background: #dbeafe; color: #1e40af; }
        .badge-completed { background: #d1fae5; color: #065f46; }
        .badge-pending { background: #fef3c7; color: #92400e; }
    </style>
</head>
<body>
    <h1>Investment Statement</h1>
    <div class="subtitle">Statement for Investment #{{ $investment->id }} &middot; Generated on {{ $generatedAt->format('d F Y \a\t H:i') }}</div>

    <h2>Investment Details</h2>
    <table>
        <tr><td>Investment ID</td><td>#{{ $investment->id }}</td></tr>
        <tr><td>Loan Reference</td><td>{{ $investment->loan->reference ?? 'N/A' }}</td></tr>
        <tr><td>Status</td><td><span class="badge badge-{{ $investment->status }}">{{ ucfirst($investment->status) }}</span></td></tr>
        <tr><td>Investment Amount</td><td>{{ $currency }} {{ number_format((float) $investment->amount, 2) }}</td></tr>
        <tr><td>Interest Rate</td><td>{{ number_format((float) $investment->interest_rate, 2) }}%</td></tr>
        <tr><td>Expected Return</td><td>{{ $currency }} {{ number_format((float) $investment->expected_return, 2) }}</td></tr>
        @if($investment->isCompleted())
        <tr><td>Actual Return</td><td>{{ $currency }} {{ number_format((float) $investment->actual_return, 2) }}</td></tr>
        <tr><td>Earnings (Profit)</td><td>{{ $currency }} {{ number_format((float) $investment->actual_return - (float) $investment->amount, 2) }}</td></tr>
        @endif
    </table>

    <h2>Loan Summary</h2>
    <table>
        <tr><td>Loan Reference</td><td>{{ $investment->loan->reference ?? 'N/A' }}</td></tr>
        <tr><td>Loan Purpose</td><td>{{ $investment->loan->purpose ?? 'N/A' }}</td></tr>
        <tr><td>Loan Term</td><td>{{ $investment->loan->loan_term_days ?? '-' }} days</td></tr>
        <tr><td>Loan Status</td><td>{{ ucfirst($investment->loan->status ?? 'N/A') }}</td></tr>
        <tr><td>Borrower</td><td>Borrower #{{ substr(md5($investment->loan->borrower_id ?? 0), 0, 8) }}</td></tr>
    </table>

    <h2>Timeline</h2>
    <table>
        <tr><td>Funded On</td><td>{{ $investment->funded_at ? $investment->funded_at->format('d F Y') : 'Pending' }}</td></tr>
        @if($investment->completed_at)
        <tr><td>Completed On</td><td>{{ $investment->completed_at->format('d F Y') }}</td></tr>
        @endif
    </table>

    <div class="footer">Generated by {{ config('app.name') }}. This statement is for record-keeping purposes only.</div>
</body>
</html>
