<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Loan Agreement {{ $loan->reference }}</title>
    <style>
        body { color: #1f2937; font-family: DejaVu Sans, sans-serif; font-size: 12px; line-height: 1.5; }
        h1 { color: #111827; font-size: 24px; margin-bottom: 4px; }
        h2 { border-bottom: 1px solid #d1d5db; color: #111827; font-size: 15px; margin-top: 24px; padding-bottom: 5px; }
        .subtitle { color: #6b7280; margin-bottom: 24px; }
        table { border-collapse: collapse; width: 100%; }
        td { border-bottom: 1px solid #e5e7eb; padding: 8px 4px; }
        td:first-child { color: #4b5563; font-weight: bold; width: 42%; }
        .footer { color: #6b7280; font-size: 10px; margin-top: 32px; text-align: center; }
    </style>
</head>
<body>
    <h1>Loan Agreement</h1>
    <div class="subtitle">Agreement Version {{ $agreementVersion }}</div>

    <table>
        <tr><td>Borrower</td><td>{{ $borrower->full_name }}</td></tr>
        <tr><td>Loan Number</td><td>{{ $loan->reference }}</td></tr>
        <tr><td>Trust Tier</td><td>{{ ucfirst($calculation->trustTier) }}</td></tr>
        <tr><td>Trust Score</td><td>{{ number_format($calculation->riskScore, 2) }}</td></tr>
        <tr><td>Loan Amount</td><td>{{ config('loans.currency') }} {{ number_format($calculation->principal, 2) }}</td></tr>
        <tr><td>Interest</td><td>{{ number_format($calculation->interestRate, 2) }}% ({{ config('loans.currency') }} {{ number_format($calculation->interestAmount, 2) }})</td></tr>
        <tr><td>Platform Fee</td><td>{{ config('loans.currency') }} {{ number_format($calculation->platformFee, 2) }}</td></tr>
        <tr><td>Lender Return</td><td>{{ number_format($lenderReturnPercent, 2) }}% ({{ config('loans.currency') }} {{ number_format($lenderReturnAmount, 2) }})</td></tr>
        <tr><td>Repayment</td><td>{{ config('loans.currency') }} {{ number_format($calculation->totalRepayment, 2) }}</td></tr>
        <tr><td>Repayment Date</td><td>{{ $repaymentDate->format('d F Y') }}</td></tr>
    </table>

    <h2>Terms</h2>
    <p>{{ $terms }}</p>

    <h2>Conditions</h2>
    <p>{{ $conditions }}</p>

    <div class="footer">Generated by {{ config('app.name') }} for loan {{ $loan->reference }}.</div>
</body>
</html>
